name: CJPP-C2xJ3xP5x-pages

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - gh-pages

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - run: npm install -D vuepress@next
      - run: npm run docs:dev